[phases.setup]
nixPkgs = ['nodejs_20', 'npm']
aptPkgs = []

[phases.install]
cmds = [
  'cd server && npm install'
]

[phases.build]
cmds = []

[start]
cmd = 'cd server && npm start'

[nixpacks]
plan-path = "./nixpacks.plan"