[build]
builder = "nixpacks"
buildCommand = "cd server && npm install -g pnpm@10.7.1 && INIT_CWD=$PWD pnpm install --no-frozen-lockfile"

[deploy]
startCommand = "cd server && pnpm start"
restartPolicyType = "on-failure"